version: "1.0"

services:
  main:
    container_name: main
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
      - "9229:9229"
    command: npm run start:prod
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:17
    env_file:
      - .production.env
    environment:
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
