FROM node:22.11-alpine

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm cache clean --force \
    && npm ci --omit=dev

COPY . .

# Сборка проекта
RUN npm run build

CMD ["npm", "run", "start:prod"]
