FROM node:22.11-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm cache clean --force \
    && npm ci --omit=dev \
    && npm i -g @nestjs/cli

COPY . .

RUN npm run build

CMD ["npm", "run", "start:prod"]
